project:
  type: website
  output-dir: docs
website:
  title: "Instructional Design for Python Programming"
  site-url: https://saintgits-tech.github.io/Instructional-Design-AlgoThink/
  repo-url: https://github.com/saintgits-tech/Instructional-Design-AlgoThink
  repo-branch: main
  repo-actions: [issue]
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd 
        text: About the FDP
      - href: feedback.qmd
        text: Feed Back  
      - text: "Resources"
        menu:
        - href: Instructional_design/Course_outline.qmd
          text: Course Outline
        - href: Instructional_design/Instru_design.qmd
          text: Instructional Design

  sidebar:
    style: "docked"
    logo: "./images/workshop_cover.png"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - href: introduction/index.qmd
        text: Introduction to Quarto
      - href: setup/index.qmd
        text: Setting-up
      - hands_on.qmd
      #- href: ML/ML_lesson.qmd
      #  text: ML Project
      - about.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
filters: 
  - pyodide
# Additional extensions for Sphinx
sphinx:
  config:
    html_js_files:
    - https://unpkg.com/mermaid@10.9.1/dist/mermaid.min.js
  extra_extensions:
    - sphinxcontrib.mermaid # Draw diagrams with Mermaid
body-header: | 
  This Cource is designed and implemented by Department of Mathematics
margin-header: |
  ![`Saintgits-Tech`- Sharing Innovations to Community](/images//saintgits_logo.JPG)