project:
  type: website
  output-dir: docs
website:
  title: "Instructional Design for Python Programming"
  site-url: https://sijuswamy.github.io/CME-workshop-1/
  repo-url: https://github.com/sijuswamy/CME-workshop-1
  repo-branch: main
  repo-actions: [issue]
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd 
        text: About the FDP
      - href: feedback.qmd
        text: Feed Back  
  sidebar:
    style: "docked"
    logo: "./images/workshop_cover.png"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - href: Instructional_design/Course_outline.qmd
        text: Course Outline
      - href: Instructional_design/Instru_design.qmd
        text: Instructional Design
      - href: introduction/index.qmd
        text: Introduction to Quarto
      - href: setup/index.qmd
        text: Setting-up
      - hands_on.qmd
      #- href: ML/ML_lesson.qmd
      #  text: ML Project
      - about.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

# Additional extensions for Sphinx
sphinx:
  config:
    html_js_files:
    - https://unpkg.com/mermaid@10.9.1/dist/mermaid.min.js
  extra_extensions:
    - sphinxcontrib.mermaid # Draw diagrams with Mermaid
body-header: | 
  This Cource is designed and implemented by Department of Mathematics
margin-header: |
  ![Sharing Innovations](/images//saintgits_logo.JPG)