---
title: "Feedback Analysis"
author: "siju.swamy@saintgits.org"
format:
    html: default
execute:
  echo: false
jupyter: python3
---

## Workshop Feedback Questionnaire

We value your feedback! Please take a moment to provide your insights on the workshop. Your responses will help us improve and tailor future sessions to better meet your needs.

### Feedback Questionnaire

Please rate the following statements on a scale of 1 to 5, where 1 is "Strongly Disagree" and 5 is "Strongly Agree":

1. **How effective was the workshop in teaching you to use Quarto for course Websites and technical writing?**
   - [ ] 1
   - [ ] 2
   - [ ] 3
   - [ ] 4
   - [ ] 5

2. **How clear was the discussions on the  Instructional Design of the Course ?**
   - [ ] 1
   - [ ] 2
   - [ ] 3
   - [ ] 4
   - [ ] 5

3. **How beneficial was the hands-on approach and tools used in the FDP?**
   - [ ] 1
   - [ ] 2
   - [ ] 3
   - [ ] 4
   - [ ] 5

4. **How would you rate the knowledge and expertise of the resource person in the topics covered?**
   - [ ] 1
   - [ ] 2
   - [ ] 3
   - [ ] 4
   - [ ] 5

5. **How satisfactory was the support and assistance provided by the resource person during the workshop?**
   - [ ] 1
   - [ ] 2
   - [ ] 3
   - [ ] 4
   - [ ] 5

Thank you for your feedback!

---

You can access the feedback form through the link below or scan the QR code to provide your responses:

<https://forms.gle/bHKwtrkV8JoN8KCc6>


{{< qrcode https://forms.gle/bHKwtrkV8JoN8KCc6 >}}


